name: xash
version: '1.0'
summary: Xash3D FWGS Engine
description: |
  Xash3D FWGS is a custom Gold Source engine rewritten from scratch.
  
grade: devel
confinement: devmode

parts:
  xash:
    plugin: nil
    source: https://github.com/FWGS/xash3d-fwgs.git
    source-depth: 1
    override-build: |
      export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
      cd $SNAPCRAFT_PART_SRC
      ./waf configure -T release
      ./waf build

    build-packages:
      - build-essential
      - python
      - libsdl2-dev:i386
      - libfontconfig-dev:i386
      - libfreetype6-dev:i386

    stage-packages:
      - libsdl2-2.0-0:i386
      - libfontconfig1:i386
      - libfreetype6:i386

apps:
  xash:
    command: bin/xash3d
    plugs: [network, home, opengl]
