name: xash
version: '1.0'
summary: xash ported to snap
description: |
  Xash3DFWGS ported to snap

grade: devel
confinement: devmode

parts:
  build:
    plugin: nil
    build-packages:
      - build-essential
      - python
      - libsdl2-dev
      - libfontconfig-dev
      - libfreetype6-dev
      - gcc-multilib
      - g++
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      wget https://waf.io/waf-2.0.22 -O waf
      chmod +x waf
      export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
      if [ "$(arch)" = "x86_64" ]; then
          ./waf configure -T release -8
      else
          ./waf configure -T release
      fi
      ./waf build

  xash:
    plugin: nil
    source: https://github.com/FWGS/xash3d-fwgs.git
    source-depth: 1
    build-packages:
      - g++
      - gcc-multilib
    stage-packages:
      - libsdl2-2.0-0
      - libfontconfig1
      - libfreetype6
      - gcc-multilib
    after: [build]
    override-prime: |
      snapcraftctl prime
      if [ "$(arch)" = "x86_64" ]; then
          apt-get download libsdl2-2.0-0:i386 libfontconfig1:i386 libfreetype6:i386
          dpkg -x libsdl2-2.0-0_*.deb $SNAPCRAFT_PART_INSTALL/usr/lib/i386-linux-gnu/
          dpkg -x libfontconfig1_*.deb $SNAPCRAFT_PART_INSTALL/usr/lib/i386-linux-gnu/
          dpkg -x libfreetype6_*.deb $SNAPCRAFT_PART_INSTALL/usr/lib/i386-linux-gnu/
      fi

apps:
  xash:
    command: bin/xash3d
    plugs: [network, home, opengl]
