name: xash
version: '1.0'
summary: xash ported to snap
description: |
  Xash3DFWGS ported to snap
  
grade: devel
confinement: devmode

parts:
  xash:
    plugin: nil
    source: https://github.com/FWGS/xash3d-fwgs.git
    source-depth: 1
    override-build: |
      export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
      cd $SNAPCRAFT_PART_SRC
      ./waf configure -T release
      ./waf build

    build-packages:
      - build-essential
      - python
      - libsdl2-dev
      - libfontconfig-dev
      - libfreetype6-dev
    architecture: [amd64, i386]

    stage-packages:
      - libsdl2-2.0-0
      - libfontconfig1
      - libfreetype6
    architecture: [amd64, i386]

apps:
  xash:
    command: bin/xash3d
    plugs: [network, home, opengl]
