name: xash
base: core20
version: '1.0'
grade: stable
confinement: strict
summary: xash ported to snapcraft
description: |
  Xash3D FWGS ported to Snapcraft.

apps:
  xash:
    command: bin/xash3d

parts:
  xash:
    plugin: nil
    source: https://github.com/FWGS/xash3d-fwgs.git
    source-tag: continuous-uncrustify
    build-packages:
      - build-essential
      - gcc-multilib
      - g++-multilib
      - python
      - libsdl2-dev
      - libfontconfig-dev:i386
      - libfreetype6-dev:i386
    stage-packages:
      - libsdl2-2.0-0:i386
      - libfontconfig1:i386
      - libfreetype6:i386
    override-build: |
      # Override the build step to use the Waf build system
      cd $SNAPCRAFT_PART_SRC
      ./waf configure -T release
      ./waf build
