name: xash
version: '1.0'
summary: xash ported to snap
description: |
  Xash3DFWGS ported to snap
  
grade: devel
confinement: devmode

parts:
  build:
    plugin: nil
    source: https://waf.io/waf-2.0.27.tar.bz2
    source-depth: 1
    build-packages:
      - build-essential
      - python
      - libsdl2-dev
      - libfontconfig-dev
      - libfreetype6-dev
      - gcc-multilib
      - g++
      - waf
      - wget

  xash:
    plugin: nil
    source: https://github.com/FWGS/xash3d-fwgs.git
    override-build: |
      export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
      export CXX=/usr/bin/g++
      cd $SNAPCRAFT_PART_SRC
      ./waf configure -T release
      ./waf build

    build-packages:
      - g++
      - gcc-multilib

    stage-packages:
      - libsdl2-2.0-0
      - libfontconfig1
      - libfreetype6
      - gcc-multilib

    after: [build]
    override-prime: |
      snapcraftctl prime
      if [ "$(arch)" = "x86_64" ]; then
          apt-get download libsdl2-2.0-0:i386 libfontconfig1:i386 libfreetype6:i386
          dpkg -x libsdl2-2.0-0_*.deb $SNAPCRAFT_PART_INSTALL/usr/lib/i386-linux-gnu/
          dpkg -x libfontconfig1_*.deb $SNAPCRAFT_PART_INSTALL/usr/lib/i386-linux-gnu/
          dpkg -x libfreetype6_*.deb $SNAPCRAFT_PART_INSTALL/usr/lib/i386-linux-gnu/
      fi

apps:
  xash:
    command: bin/xash3d
    plugs: [network, home, opengl]
